src/clear/model/collection.cr

Just added a missing `!` to an otherwise broken `.not_nil!`

Add missing ! in Collection#[]

---

spec/init_pg.sh
spec/migration/migration_spec.cr
spec/model/model_spec.cr
src/clear/migration/manager.cr

When going through a POC without dropping the DB in between runs, ran into a bug on subsequent runs when it tried to apply the DummyMigration again (and record that it was applied).

Fix bug when applying migrations repeatedly

---

spec/model/model_spec.cr
src/clear/model/modules/has_saving.cr

Wraps the `save` method in a begin/rescue/else block.  This allows the `persisted` variable to only be set to true if there was no exception raised from the db insert.
This fixes #39

Only set persisted = true if there were no exceptions

---

src/clear/sql/sql.cr

Adding a add_connection method to SQL. This allows you to create a new connection after the initial instantiation.
We have a case where we need to connect to a different database based on what libraries in are shard are being required.
I've tested locally with this change and have not had any issues.

A method to add a new connection after instantiation.

---

spec/model/cache_spec.cr
spec/model/model_spec.cr
src/clear/model/modules/has_columns.cr

Revamp the `Model#set` method when usage of NamedTuple.
The behavior of `Model#set` is now changing according to this rule:
- If a hash is passed as parameter, it will ignore the fields which are not columns
- If a NamedTuple is passed as parameter, it will try to call all setter related to the fields which exists in the model. This allow to create model passing non-persisted fields value in `create` and `build`.
This should also improve slightly the performance of the ORM when creating model using NamedTuple, as NamedTuple is not casted to hash before processing anymore.

Add virtual field support (fix #68)

---

src/clear/error_messages.cr
src/clear/sql/logger.cr

There were a few typos and grammatical errors in the error messages. This commit cleans those up.
This makes some of the error messages a little easier to understand, and adds a bit of polish to the shard.
- [ x ] Typo changes
NOTE: ameba actually fails, but not on this file. I can fix those, but I feel like that should be done in a separate commit.

fixing some typos and misspellings in the error messages.

---

spec/model/uuid_spec.cr
src/clear/model/column.cr
src/clear/model/converter/uuid_converter.cr
src/clear/model/modules/has_columns.cr
src/clear/model/modules/relations/belongs_to_macro.cr

Fix #74 problem with `belongs_to` having `foreign_key` which is not a type of the union Clear::SQL::Any.
It change the conversion system by adding the conversion module as generic parameter in the column itself, and adding two methods in the column: `to_sql_value` and `reset_convert`.
- `to_sql_value` returns the value of the column after the field has been converted to a type belonging to Clear::SQL::Any.
- `reset_convert ` allow to pass Clear::SQL::Any in input of the column and will store the converted value if conversion is necessary.

Fix #74 problem with `belongs_to` 

---

README.md
spec/model/model_spec.cr
src/clear/model/modules/class_methods.cr
src/clear/sql/errors.cr

fixes #94
Opt to use a Clear provided RecordNotFoundError class when performing a dangerous find!. This has the advantage of allowing the consumer to use error paths to control handling of unresolved records.
Same approach as https://api.rubyonrails.org/classes/ActiveRecord/RecordNotFound.html
Allows a consumer to handle unresolved find! calls through their error handling paths rather than relying on the generic NilAssertion error currently raise.
Unit test added
^ _technically_ breaking, exposed error method has been changed.
^ Unchanged but happy to add this.

Raise RecordNotFoundError for find!

---

spec/model/uuid_spec.cr
src/clear/model/modules/relations/has_many_macro.cr
src/clear/model/modules/relations/has_many_through_macro.cr

This fix should allow has_many and has_many_through relations work on tables with UUID pkeys, not just the belongs_to mapping.
#74 
Added tests to the spec, and compiled against my own project.
I have not tested the has_many_through but in theory it should work? I think more tests are needed.

UUID associations fixes

---

spec/model/model_spec.cr
spec/model/uuid_spec.cr
src/clear/model/collection.cr
src/clear/model/modules/has_relations.cr
src/clear/model/modules/relations/belongs_to_macro.cr
src/clear/model/reflection/column.cr

- Cannot be nil unless the relation is declared as `Relation?` 
- This will enforce presence on the foreign key
- This will disallow nil attribution for the relation etc...
Crystal lang enforces type checking on compile time; Clear enforces it by using column wrapping system which allow the columns to be in a `undefined` stats instead of nil. But `belongs_to` were currently not enforced and the relations was nilable
In progress. I'll test this branch on my prod project, eventually build some tests to ensure it works.

Fix #93 `belongs_to` 

---

src/clear/model/modules/has_serial_pkey.cr

Fixes syntax error, now correctly lists out available key types
Simple bug fix
1. Changed a model to an invalid primary key type `:asdf`
2. Observed syntax error being shown
3. Applied fix
4. Correct available types now listed when invalid type is passed.

Fixes syntax error in primary key error message

---

shard.lock
shard.yml
src/clear/expression/expression.cr
src/clear/sql/query/aggregate.cr

When running a count on the query, the parent query is using the default connection instead of the one provided.
Adding a use_connection on the count query.
Locally for now. 
- [X ] Bug fix (non-breaking change which fixes an issue)

Count queries need to use the same connection as the sub query.

---

manual/querying/the-collection-object/filter-the-query-1/ordering.md

This seems to be a simple typo. I am new to Clear ORM and by going through the docs I spotted this.

changed hash to usr

---

src/clear/migration/migration.cr
src/clear/migration/operation/execute.cr

```crystal
class CreateUser
include Clear::Migration
def change(direction)
direction.up do
execute("CREATE TABLE users...")
end
direction.down do
execute("DROP TABLE users")
end
end
end
```
Up migration works well.
Down migration never executes because `execute` method accepts 2 arguments `up` and `down`. Why?
As temporary solution `execute(nil, "DROP TABLE my_models")` can be used. But without reasons.

fix Clear::Migration::Execute

---

spec/model/model_spec.cr
src/clear/migration/migration.cr
src/clear/model/collection.cr
src/clear/sql/delete_query.cr
src/clear/sql/select_builder.cr
src/clear/sql/sql.cr

I'm trying to implement tagging from scratch in Clear.
First error when calling `#unlink` method:
```
Showing last frame. Use --error-trace for full trace.
In lib/clear/src/clear/model/collection.cr:428:28
428 | @cached_result.try &.remove(item)
^-----
Error: undefined method 'remove' for Array(Tag)
```
I believe it's just a typo.
Second error:
```
Unhandled exception: You're trying to construct an invalid SQL request:
Delete Query must have a `from` clause.
You may want to check the manual:
https://github.com/anykeyh/clear/tree/master/manual/querying/RequestBuilding.md
You may also have encountered a bug. 
Feel free to submit an issue: 
https://github.com/anykeyh/clear/issues/new
```
I noticed that `delete` functionality is outdated/broken.
I'm not sure why `def delete(connection : …

fix delete and unlink

---

src/clear/model/converters/time_converter.cr

This PR adds a case to parse dates formated like ```2020-02-22T09:11:42.476953Z```

Add new time format with microseconds

---

spec/model/converter_spec.cr
src/clear/extensions/uuid/uuid.cr

Right now when you insert an uuid property with nil, it transforms it into an empty string instead.
This PR fixes that, now inserting an uuid with nil inserts NULL in the database.

inserting uuid properties with nil now works

---

src/clear/model/converters/time_converter.cr

I've managed to simplify a bit the time converter, now it only uses a regex for "2020-02-22 09:11:42.476953" which is not an RFC_3339 format, all the other cases (and more since I had other format errors) can be handled with the stdlib directly.
I've not touched the specs to show that parsing still works.

simplify time converter

---

src/clear/sql/transaction.cr

Crystal 0.35.0 changed something with Proc parsing to where Proc literals now require parens around them, this PR fixes that.
Crystal 0.35.0 breaking change
It has been tested in my environment and is working with this change

Crystal 0.35.0 fix; Procs literals require parens

---

shard.lock
spec/spec_helper.cr
src/clear/core.cr
src/clear/migration/migration.cr
src/clear/sql/logger.cr

Upgrade to Crystal 0.35.0
Dependencies just need to be updated and there was an easy fix for deprecation warnings coming from https://github.com/crystal-lang/crystal/pull/8847
Passing the test suite

Upgrade to Crystal 0.35.0

---

src/clear/sql/sql.cr

Fixing:
```
Showing last frame. Use --error-trace for full trace. 
In lib/clear/src/clear/sql/insert_query.cr:61:10                                                          
61 | h[col] = rs.read                                                                                    
^                  
Error: no overload matches 'Hash(String, Array(JSON::Any) | Array(PG::BoolArray) | Array(PG::CharArray) | Array(PG::Float32Array) | Array(PG::Float64Array) | Array(PG::Int16Array) | Array(PG::Int32Array) | Array(
PG::Int64Array) | Array(PG::NumericArray) | Array(PG::StringArray) | Array(PG::TimeArray) | Bool | Char | Clear::Expression::UnsafeSql | Float32 | Float64 | Hash(String, JSON::Any) | Int16 | Int32 | Int64 | Int8 
| JSON::Any | PG::Geo::Box | PG::Geo::Circle | PG::Geo::Line | …
```

fix compatibility with latest crystal-pg

---

README.md
manual/model/column-types/model-definition.md
spec/model/converter_spec.cr
spec/model/model_spec.cr
src/clear/migration/migration.cr
src/clear/migration/operation/table.cr
src/clear/model/collection.cr
src/clear/model/converters/number_converters.cr
src/clear/sql/sql.cr

- Add `[BigDecimal](https://crystal-lang.org/api/0.35.1/BigDecimal.html)` converter.
- Allow `[Numeric](https://www.postgresql.org/docs/9.6/datatype-numeric.html) (Arbitrary Precision Numbers)` type in migration (e.g. `numeric`, `numeric(10)`, `numeric(10, 5)`)
- Map `BigDecimal` (in `.cr`) to `Numeric` (in `pg`) in migration columns (i.e. declaring column data type as `"bigdecimal"` would be equal to the column being declared with type `"numeric"`, if you wish to specify precision, and scale, please use `"numeric(precision, scale)"` or `"numeric(precision)"` (with scale defaulting to 0), instead of `"bigdecimal"`)
- For usage of `BigDecimal`, please consult Crystal docs as specified in the first bullet point.
- For usage of `Numeric`, please consult PostgreSQL docs as specified in the …

Add bigdecimal (.cr) mapping to numeric (pg) in converter and migration

---

spec/model/model_spec.cr
src/clear/model/json_deserialize.cr
src/clear/model/model.cr
src/clear/model/modules/has_columns.cr

Co-authored-by: Caspian Baska <caspian@place.tech>
- Add support for creating and updating models from json, with mass assignment protection.
- These have been documented inline
- The model methods added are listed as follows:
`Model.from_json(json, trusted=true)`
`Model#set_from_json(json, trusted=false)`
`Model.create_from_json(json, trusted=false)`
`Model.create_from_json!(json, trusted=false)`
`Model#update_from_json(json, trusted=false)`
`Model#update_from_json!(json, trusted=false)`
- In the `column` macro, `mass_assign : Bool (default = true`) as an additional params has been added. This allows for protecting mass assignment when instantiating or updating a new model from json through `.from_json` methods from this module. Since `trusted` is false by default, mass assignment …

Add create/update/set from JSON

---

spec/model/relations/fixture.cr
src/clear/model/modules/relations/has_one_macro.cr

`has_one foo : Foo?` currently fails to compile with error `method must return ShardMetrics but it is returning Bool`. This patch is a simple fix. I didn't add a functional spec, but this should be good enough.

Fix has_one getter for nilable type

---

src/clear/extensions/enum/migration.cr
src/clear/model/modules/has_relations.cr
src/clear/model/reflection/column.cr

There were 2 issues:
1. The first, 653c74c9b15a7d9f5f145279bbec5763fa28785b, was causing compilation to fail. I didn't investigate further because this module was clearly incorrectly (it was defining `Clear::Migration::Clear::Migration::Helper`).
2. The second issues only affected `has_many` and `belongs_to` associations which were nilable (and defined using the `?` shorthand). The reason for the breakage and a minimal fix is included in 0aa9beb7704728e37bfe07ce7c241bb3959b9660.  A more robust fix is then added in 8cc27f72235d55fd7c7cf4d09d2b0ddb9664d598, but with the caveat that some code may need to be updated with additional `require`s (so that the union type can be resolved in the macro). I would be happy to remove 8cc27f72235d55fd7c7cf4d09d2b0ddb9664d598 from this PR in order to get …

Fix breakages caused by Crystal 1.13

---

spec/model/converters/json_converter_spec.cr
src/clear/model/converters/json_any_converter.cr

Currently the literal string `'null'` is written to the database when a `nil` value is serialized.
Note that the `json_serializable_converter` macro already does the right thing: https://github.com/anykeyh/clear/blob/master/src/clear/model/converters/json_any_converter.cr#L59
A test has been added.
There were no existing tests for `Clear::Model::Converter::JSON::AnyConverter.to_db`.

Fix serialization of JSON::Any? nil values

---

manual/model/column-types/converters.md
spec/model/converters/custom_converter_spec.cr

- Add spec demonstrating working custom converter detailed in the manual
- To clarify custom converter working in action
- Spec added in `spec/model/converters/custom_converter_spec`
- All specs passed

Add custom converter spec detailed as example in the manual

---

spec/model/model_spec.cr
src/clear/model/json_deserialize.cr

- Full detail of issue here: https://github.com/anykeyh/clear/issues/202
- This issue is a simple error due to the use of `COLUMNS` key for declaring instance variables, which is assigned as follows:
https://github.com/anykeyh/clear/blob/3bdaa44a7d0382fd8f6846afe8b8da95d58d9452/src/clear/model/modules/has_columns.cr#L174
The key is assigned to the method name, `name.var` by default but will be re-assigned to `column_name.id` if declared, which is the name of the column in the database, not the name of the method.
We need to use the method name and not the column_name, hence the change from `{{name.id}}` to `{{settings["crystal_variable_name"]}}`
- Resolves https://github.com/anykeyh/clear/issues/202
- All specs passed

Fix JSON::Deserialize not working with column_name field
